### ISSUE TITLE
'initJNIThread' is not GC-safe

### ISSUE THREAD

**Issue by TensorTom** [iffy/wiish#64]
Trying to `wiish run --android` produces:

```
DEBUG nim c --os:android -d:android --cpu:arm -d:appJavaPackageName=org.wiish.webviewexample --noMain --gc:regions --header --threads:on --hints:off --compileOnly --nimcache:dist/android/project/org.wiish.webviewexample/app/jni/src/armeabi-v7a ./main_mobile.nim
/home/tensortom/.nimble/pkgs/jnim-0.4.2/private/jni_api.nim(67, 18) Error: 'initJNIThread' is not GC-safe as it performs an indirect call here
/tmp/nimble_12224/githubcom_iffywiishgit/wiishpkg/building/buildutil.nim(31) run
Error: unhandled exception: Error running process [CatchableError]
```

I have the Android sdk properly installed. `wiish doctor` shows green checkmarks.

**Comment by iffy** [comment]
I've seen this before... I wonder if it's a jnim problem.  Can you try with jnim 0.5.0?

Something like this might work:

```
git clone https://github.com/yglukhov/jnim.git
cd jnim
nimble develop
```

If that makes it work, I think maybe we need to check for more things in `wiish doctor`

**Comment by iffy** [comment]
It is jnim.  I've updated the `wiish.nimble` file to require jnim>=0.5 after duplicating the error by using jnim 0.4.2.  Let me know if upgrading jnim doesn't work for you.
